### Register user
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "eko",
  "password": "eko123",
  "name": "Eko"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "eko",
  "password": "rahasia"
}

### Get User
GET http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Logout User
DELETE http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: fa2b5382-3301-4ca4-a214-9b934deaa8c5

### Update User
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 8bc7d012-668a-4dfa-b279-0c3f3f25b6fb

{
  "name": "Eko Kurniawan"
}

### Update User Password
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 8bc7d012-668a-4dfa-b279-0c3f3f25b6fb

{
  "password": "rahasia"
}

### Create Contact
POST http://localhost:3000/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

{
  "first_name": "Budi Kurniawan",
  "last_name": "Khannedy",
  "email": "eko@example.com",
  "phone": "099123123213"
}

### Update Contact
PUT http://localhost:3000/api/contacts/130
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

{
  "first_name": "Eko",
  "last_name": "Khannedy",
  "email": "eko@example.com",
  "phone": "099123123213"
}

### Get Contact
GET http://localhost:3000/api/contacts/130
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Remove Contact
DELETE http://localhost:3000/api/contacts/130
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Search Contact
GET http://localhost:3000/api/contacts
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Add Address
POST http://localhost:3000/api/contacts/131/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

{
  "street": "Jalan B",
  "city": "Jakarta",
  "province": "DKI Jakarta",
  "country": "Indonesia",
  "postal_code": "13123"
}

### Get Address
GET http://localhost:3000/api/contacts/131/addresses/64
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Update Address
PUT http://localhost:3000/api/contacts/131/addresses/64
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

{
  "street": "Jalan C",
  "city": "Bandung",
  "province": "Jawa Barat",
  "country": "Indonesia",
  "postal_code": "34534"
}

### List Address
GET http://localhost:3000/api/contacts/131/addresses
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118

### Remove Address
DELETE http://localhost:3000/api/contacts/131/addresses/64
Accept: application/json
X-API-TOKEN: 617df9de-e251-4b78-a71c-4fbd28550118